### PR TITLE
Allow for optional per-module pre-transform.

### PR DESCRIPTION
**Pull request by leebyron**
Use case: I want to use flow for type checking, but acorn (rightly) doesn't parse the type hints. I need to strip the typehints before calling esperanto. However, esperanto reads directly from disk. So now I must first build a temp directory and build a parallel type-hint-stripped src tree and provide that to esperanto. Yuk.

This change allows for a "transform" step, not too dissimilar from the same functionality in browserify. Now, instead of mucking with temp files, I can just provide a source to source function that does type hint stripping.

Because of it's placement, `options.transform` can return either a Promise or String.

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Thanks, this makes sense. It does mean that sourcemaps are no longer accurate if a transform is supplied, but I guess that's a fair price. Can cross that bridge when we come to it

**Comment by leebyron** [comment]
Correct. It probably makes sense to borrow the contract from browserify for source mapped transforms

**Comment by Rich-Harris** [comment]
Do you mean that each step includes an inline sourcemap? I've had some success resolving a sourcemap chain at the end of the process (https://github.com/Rich-Harris/sorcery) which means that transpilers don't need to know anything about incoming sourcemaps - though frankly the whole thing makes my brain hurt.

Just released 0.5.8 with the `transform` option

**Comment by leebyron** [comment]
Another great use of this popped-up. In the pre-bundle transform I can introduce new `includes` and it just works.

Taking advantage of this while shaving bytes from the payload for immutable - https://github.com/facebook/immutable-js/blob/master/resources/declassify.js#L130

**Pull request merged**
