### PR TITLE
_evilES3SafeReExports: Fix ES3 syntax error for default re-exporting

### LINKED ISSUE #175: export { default } from '...' causing parse error in IE8.
This is an issue in ember-wormhole, and liquid-fire. When directly exporting a component with `export { default } from 'somewhere/component-name'` It outputs `exports.default = component-name.default;` which causes a parse error in IE8. 

The [current solution](https://github.com/ef4/liquid-fire/issues/311) courtesy of @rwjblue is found

    // change 
    export { default, measure } from "liquid-fire/components/liquid-measured";
    // which outputs:
    exports.default = liquid_measured.default; // IE8 Parse Error
    exports.measure = liquid_measured.measure;

    // to 
    import LiquidMeasured, { measure } from 'liquid-fire/components/liquid-measured';

    export default LiquidMeasured;
    export { measure };
    // which outputs 
    exports['default'] = liquid_measured['default'] // works in IE8.
    exports.measure = liquid_measured.measure;

@stefanpenner suggested in a [PR](https://github.com/yapplabs/ember-wormhole/pull/17) that this was a issue with esperanto and to report here.

### PR DESCRIPTION
**Pull request by XrXr**
Fixes #175

### CODE REVIEW

**Comment by stefanpenner** [comment]
:+1:

**Comment by XrXr** [comment]
@Rich-Harris could you review this? We, and I think many others are waiting for this to be merged so It can be fixed in Ember CLI so we can support IE8 on its way out.

**Comment by stefanpenner** [comment]
> @Rich-Harris could you review this? We, and I think many others are waiting for this to be merged so It can be fixed in Ember CLI so we can support IE8 on its way out.

please note, it appears the windows tests are failing. Could you look into this?

**Comment by XrXr** [comment]
@stefanpenner I looked at the console output from appveyor. `nodejs_version=0.10` and `nodejs_version=0.12` couldn't connect to Github. The one that has fail tests is `nodejs_version=1.0`

AFAIK Node.js doesn't have a 1.0 at the moment. Is it IO.js?

**Comment by XrXr** [comment]
I looked into a little, I think the failed tests are inherited from `mast`.

https://ci.appveyor.com/project/eventualbuddha/esperanto/build/1.0.181

I ran the console output of the master branch build and the build for this PR through a difftool, and the fail messages are exactly the same.

**Comment by stefanpenner** [comment]
@eventualbuddha can we move this forward?

**Comment by stefanpenner** [comment]
I now have commit and publish, so lets get this moving.

It does appear like the appveyor build has never passed. So it should not block this bugfix.

**Comment by alexlafroscia** [comment]
For people seeing issues with the Ember CLI that this should fix, what would be the right way to get this patch now?

**Comment by stefanpenner** [comment]
> For people seeing issues with the Ember CLI that this should fix, what would be the right way to get this patch now?

tricky, it appears something if wrong with esperantos build preventing me from releasing.

I would suggest just running your prod build output through https://github.com/stefanpenner/es3-safe-recast

**Comment by alexlafroscia** [comment]
Alright, thanks! I'll keep an eye open for an Esperanto update in the near future, too.

**Pull request merged**
