### PR TITLE
Add _evilES3SafeReExports option to allow evil ES3 re-exports.

### PR DESCRIPTION
**Pull request by rwjblue**
Fixes https://github.com/esperantojs/esperanto/issues/84.

### CODE REVIEW

**Comment by rwjblue** [comment]
Many of these changes (dist/) are from prior PR's/commits where dist/ was not checked in. Do I need to remove them from my PR?

**Comment by Rich-Harris** [comment]
Awesome, thanks @rwjblue.

Nah, I don't think it's worth worrying about the dist files - I reckon a better option is remove them from the repo altogether and have Travis sort it out, otherwise it'll keep happening. We do this with [Ractive](https://github.com/ractivejs/ractive) - on each push to the `dev` branch, if the tests pass then Travis updates the [`build` branch](https://github.com/ractivejs/ractive/tree/build) which just contains dist files, README and *.json gubbins. Keeps the repo clean and the .tar file small. Will create an issue for it

**Comment by Rich-Harris** [comment]
@eventualbuddha I was just about to merge this but the AppVeyor build failed - is that something to worry about? It looks like AppVeyor might be down

**Comment by rwjblue** [comment]
@eventualbuddha mentioned in https://github.com/esperantojs/esperanto/issues/78#issuecomment-71488963 that there was an issue with AppVeyor. I'm not sure if it is sorted out just yet....

**Comment by rwjblue** [comment]
@eventualbuddha / @Rich-Harris - Any updates? Is there anything I can do to help (changed approach, other updates, etc)?

**Comment by Rich-Harris** [comment]
@rwjblue yep, sorry - I was going to merge before but got hung up on the AppVeyor thing, then got tied up with work. Merging now as it looks as though that's a separate issue with the AppVeyor setup

**Comment by Rich-Harris** [comment]
Released 0.6.7 with this change

**Pull request merged**
