### PR TITLE
[Bugfix] re-exports should remain enumerable

### PR DESCRIPTION
**Pull request by stefanpenner**
cc @ef4 this should fix liquid-fire's proxy-like module

### CODE REVIEW

**Comment by stefanpenner** [comment]
i can't seem to get the  `es6-module-transpiler-tests` to actually run... any advice?

cc @eventualbuddha

**Comment by Rich-Harris** [comment]
Thanks. How do you mean you can't get the tests to run? If you just run `mocha` or `npm test` (same thing) it should run *all* the tests, including the es6-m-t ones

**Comment by stefanpenner** [comment]
> Thanks. How do you mean you can't get the tests to run? If you just run mocha or npm test (same thing) it should run all the tests, including the es6-m-t ones

I mean, i didn't know where to put the failing test case for this one.

**Comment by Rich-Harris** [comment]
Ah, okay. I guess there's a slightly larger issue there - the test suite is slightly arbitrarily split into those tests that ensure formatting is consistent (`samples` and `bundle/input`), and those that actually make assertions about the transpiled code (`es6-module-transpiler-tests`). I've only been adding new tests to `samples` and `bundle/input`, I guess because I wanted to be able to update `es6-module-transpiler-tests` from source without worrying about the ones I'd added, which is possibly an outdated concern. But including assertions in the actual code is self-evidently a better approach.

Have just added #83 for this

**Pull request merged**
