### PR TITLE
report external modules as bundle.external

### LINKED ISSUE #59: Report external modules
See https://github.com/ef4/broccoli-es6modules/pull/4#issuecomment-69940889. It would be useful to report which external modules are required by a bundle. Something like

```js
esperanto.bundle( bundleOptions ).then( function ( bundle ) {
  console.log( 'external dependencies: ' + bundle.external.join( ', ' ) );
  doSomethingWith( bundle.external );
  fs.writeFileSync( 'bundle.js', bundle.toAmd(...) );
});
```

### PR DESCRIPTION
**Pull request by Rich-Harris**
This closes #59

### CODE REVIEW

**Comment by stefanpenner** [comment]
friendly reminder

**Comment by Rich-Harris** [comment]
Ha, haven't forgotten! Just been tied up - schedule should be more forgiving as of tomorrow...

**Comment by stefanpenner** [comment]
can we get both a list of imports/exports so other tooling can easily validate across all modules without having to re-parse?

**Comment by Rich-Harris** [comment]
@stefanpenner 

> can we get both a list of imports/exports so other tooling can easily validate across all modules without having to re-parse?

How do you mean exactly? For the bundle as a whole, or individual modules?

* Would `bundle.external` be better as `bundle.imports`?
* Should there be a `bundle.exports` array with a list of bindings exported from the bundle's entry module? Is that what you're saying?

**Comment by stefanpenner** [comment]
> Would bundle.external be better as bundle.imports?

im indifferent

> Should there be a bundle.exports array with a list of bindings exported from the bundle's entry module? Is that what you're saying?

exports yes, that would be quite handy

**Comment by Rich-Harris** [comment]
Merged and documented https://github.com/esperantojs/esperanto/wiki/Bundling-multiple-ES6-modules#getting-information-about-the-bundle

**Pull request merged**
