### PR TITLE
Fix #145 - export {foo as bar}.

### LINKED ISSUE #145: export-as-from imports using the exported name
```javascript
export { foo as bar } from "mod";
```

gives (on http://esperantojs.org/)

```javascript
Object.defineProperty(exports, 'bar', { enumerable: true, get: function () { return mod.bar; }});
```

It should be

```javascript
Object.defineProperty(exports, 'bar', { enumerable: true, get: function () { return mod.foo; }});
```

### PR DESCRIPTION
**Pull request by mbostock**
Fixes #145. I’m not really sure this is the right fix, but it seemed to work?

Note: I purposely did not include the built changes to dist/. I’m assuming you’d like to test on your end, but I can include them if you want.

### CODE REVIEW

**Comment by mbostock** [comment]
Related question: is there any particular reason to use getters when defining the export object, rather than just static files? Like, instead of:

```js
var index_js = {
  get mouse () { return mouse; },
  get namespace () { return namespace; },
  get namespaces () { return namespaces; },
  get requote () { return requote; },
  get select () { return select; },
  get selectAll () { return selectAll; },
  get selection () { return Selection; },
  get touch () { return src_touch; },
  get touches () { return src_touches; }
};
```

You could produce:

```js
var index_js = {
  mouse: mouse,
  namespace: namespace,
  namespaces: namespaces,
  requote: requote,
  select: select,
  selectAll: selectAll,
  selection: Selection,
  touch: src_touch,
  touches: src_touches
};
```

**Comment by eventualbuddha** [comment]
@mbostock I believe it's because ES6 imports and exports are live bindings, so if you make a module object (i.e. `import * as foo from 'foo'`) then the properties on it will need to update their values when they change. Here's an example:

```js
// a.js
export var count = 0;
export function increment() { count++; }

// b.js
import * as a from './a';
console.log(a.count); // 0
a.increment();
console.log(b.count); // 1
```

**Comment by mbostock** [comment]
Ah, of course: [bindings, not values](https://github.com/esperantojs/esperanto/wiki/Bindings). Thanks! (And hi!)

**Comment by eventualbuddha** [comment]
Hey Mike! Nice to run into you here. I'll have to check out d3-bundler.

**Comment by Rich-Harris** [comment]
Thanks @mbostock, I've added a regression test and released this as 0.7.1. There is an `_evilES3SafeReExports` option which uses static values instead of getters in the case of one-to-one transformations - it could possibly be extended to cover bundles as well.

That said, I was thinking about d3-bundler on the way home and I think there might be a simpler way that sidesteps the issue... let me run a couple of experiments.

**Comment by mbostock** [comment]
:+1: Thanks for adding more tests. I tested against master and it still appears to work, but please `npm publish` when you get a chance.

**Comment by Rich-Harris** [comment]
Oops, thought I had, sorry - it's published now

**Pull request merged**
