### PR TITLE
[RFC] Only alter Identifiers to avoid conflict.

### PR DESCRIPTION
**Pull request by leebyron**
This is just a request for consideration, so treat it as such. All tests pass, but that doesn't mean I haven't missed something important. Lookin' for feedback!

The concept here is to do as little modification as possible to the original source, only doing so to avoid conflicts within a scope.

This also fixes an issue where all of the top-level scope is accessible, regardless of being exported. It patches this issue by modifying the names of non-exported top-level Identifiers within a module. See added test which fails before this diff.

### CODE REVIEW

**Comment by eventualbuddha** [comment]
I'd be interested in helping with this to the extent it makes sense.

**Comment by Rich-Harris** [comment]
@eventualbuddha Awesome! For the *most* part, 0.5.x is already much more relaxed about renaming identifiers, while still avoiding clashes. External modules are still a bit messy, and there are some edge cases where e.g. `var foo = ...` and `function foo () {...}` exist in the same module, but by and large it does the sensible thing.

I think my main priority at the moment, once the last few outstanding issues are closed, is to make the internals a bit less bewildering and to avoid unnecessary work (e.g. checking that identifiers aren't being replaced with the same string).

@leebyron btw I had a crack at using Esperanto in place of Smash with Immutable.js, but ran into cycles hell and put it to one side. From the comment breadcrumbs I gather you've been there too...

**Comment by leebyron** [comment]
Yes, I have some interesting circular dependencies that can be solved by careful placement in a single file (smash), but not by ES6 modules. I plan on refactoring to solve the cycle to ready for using modules directly.

**Comment by leebyron** [comment]
I'm going to close this now that you've covered basically everything in it! The output reads so nice now, great work over the last couple weeks!

**Comment by Rich-Harris** [comment]
Thanks! Grateful for the help and input

**Pull request closed without merging**
