### PR TITLE
Module environment GetThisBinding always returns undefined

### PR DESCRIPTION
**Pull request by leebyron**
https://people.mozilla.org/~jorendorff/es6-draft.html#sec-module-environment-records-getthisbinding

Any `this` expression that's not within another declarative environment (non-arrow functions) should resolve to `undefined`.

Rather than relying on a function clojure in a bundle to provide the correct environment, instead replace these instances directly (better for minifiers as well)

This means the CJS builder can be much leaner.

This also fixes a bug where variables declared within an arrow function were not being scoped correctly.

### CODE REVIEW

**Comment by leebyron** [comment]
This is going to probably conflict slightly with #42. I'll resolve the latter if either lands first.

**Comment by Rich-Harris** [comment]
Aaaahhhh, that's much nicer. Thanks for pointing towards the spec - I was under the mistaken impression that `this` meant 'the global object' inside an ES6 module. Assigning to or reading from top-level `this` should probably be a parse error - will raise a separate issue

**Comment by leebyron** [comment]
I think "use strict" covers the appropriate reading and writing from the environment object. Modules are still allowed to have those, I don't think they're supposed to be parse errors

**Comment by leebyron** [comment]
Oh I understand you're saying. any `this.foo` expression where `this` is referring to the environment this is going to result in a runtime error. I agree it would be nice to catch that at compile time.

**Pull request merged**
