### PR TITLE
Allow using `exports` as a top-level binding name.

### LINKED ISSUE #74: AMD callback name selection prevents usage of local variables with same name.
Input:

```javascript
var exports = {};

export default exports;
```

Output:

```javascript
define(['exports'], function (exports) {

	'use strict';

	var exports = {};

	exports['default'] = exports;

});
```

---

The callback arguments should not use a name that conflicts with variables in the local scope.

### PR DESCRIPTION
**Pull request by eventualbuddha**
This works with everything except UMD, will look at that later. Thoughts on strategy, specifically the IIFE in CJS?

Fixes #74.

### CODE REVIEW

**Comment by rwjblue** [comment]
Awesome, thank you!

**Comment by Rich-Harris** [comment]
@eventualbuddha just catching up on everything from yesterday. you :metal:! Unfortunately this fix *doesn't* work for bundles, only one-to-one conversions. I went with the opposite approach - renaming the locally declared `exports` object rather than the environment-provided `exports`.

I've pushed the branch I had locally - [deconflict-exports](https://github.com/esperantojs/esperanto/compare/deconflict-exports?expand=1).

As well as working with bundles, it also means the CJS IIFE is unnecessary - we can continue to use the built-in `exports`. It just becomes this:

```js
'use strict';

var _exports = {}; // <- renamed
_exports.foo = 'bar';

exports['default'] = _exports;
```

Does that seem like a good approach?

**Comment by eventualbuddha** [comment]
@Rich-Harris Your solution is probably the better approach here. Feel free to revert mine and merge yours. While you're at it, it's probably a good idea to review my approach to the other two fixes from yesterday. After that, let's cut a release :smile:

**Comment by Rich-Harris** [comment]
Cool - about to go offline and be in meetings for most of the day, but yes let's get that release out today

**Pull request merged**
