### PR TITLE
enhance parse error message to give file name

### PR DESCRIPTION
**Pull request by BryanCrotaz**

### CODE REVIEW

**Comment by eventualbuddha** [comment]
This project has been deprecated in favor of [rollup](https://github.com/rollup/rollup).

@Rich-Harris, Github now allows repos to be archived. Maybe you should do that?

**Comment by BryanCrotaz** [comment]
However there are circumstances where rollup doesn't work, and I have one of those. Still using es6-modules until rollup is fixed.

**Comment by BryanCrotaz** [comment]
so it would be lovely if you could just merge this trivial fix

**Comment by eventualbuddha** [comment]
> However there are circumstances where rollup doesn't work, and I have one of those.

Did you file a bug with rollup? Maybe it can be fixed if you do. I’ll leave it to @Rich-Harris to decide whether to merge this and do another release, since I don’t think I have npm access.

**Comment by BryanCrotaz** [comment]
I've commented on the issue to say that I'm also experiencing it

**Pull request closed without merging**
